[workspace]
channels = ["conda-forge"]
name = "lei_mockup_generator"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
imagemagick = ">=7.1.1_47,<8"
r-base = ">=4.5.1,<4.6"
